# Generated by Django 4.2.2 on 2023-07-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_category_product_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Types',
        ),
    ]
