# Generated by Django 4.2.2 on 2023-07-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_type_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
