# Generated by Django 4.2.2 on 2023-07-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
