# Generated by Django 4.2.2 on 2023-07-06 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category'),
        ),
    ]
